apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: slave
  name: 'jenkins-slave-prg-multi'
  namespace: 'its-jenkins-prod'
spec:
  imagePullSecrets:
  - name: artifactory
  - name: internal
  containers:
  - name: fortify # First container definition, name used for reference
    image: docker.artifactory.dhl.com/fortify/fortify-cloudscan-client:latest
    tty: true
    command:
    - cat # Ensures the container are ready to run commands
    resources: # Resources can be left as is
      requests: # changes must be tested, not all scenarios work
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 2000m
        memory: 4Gi
    imagePullPolicy: Always
    workingDir: "/var/lib/jenkins"
