name: Fortify Scan - MeinService TL

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fortify:
    runs-on: arc-small-container
    container:
      image: docker.artifactory.fpl.com/fortify/fortify-cloudscan-client:latest
      options: --memory=4g
    env:
      HOME: /opt/fortify
      SCA_VM_OPTS: -Xmx2750M
      JAVA_TOOL_OPTIONS: -Duser.home=/opt/fortify
      BUILD_ID: salesforce-${{ github.run_id }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SFDX_AUTH_URL_TL }}" > sfdx_auth.txt
          sf org login sfdx-url --sfdx-url-file sfdx_auth.txt --alias tl-org --set-default
          sf org display --target-org tl-org

      - name: Retrieve Metadata
        run: |
          mkdir -p code
          sf project retrieve start \
            --metadata ApexClass \
            --metadata ApexTrigger \
            --metadata ApexPage \
            --metadata AuraDefinitionBundle \
            --metadata LightningComponentBundle \
            --metadata ApexComponent \
            --metadata StaticResource \
            --target-org tl-org \
            --output-dir code

      - name: Remove Test Classes from Fortify Scan
        run: |
          rm -f code/classes/*Test.cls*
          rm -f code/classes/**/TEST_*.cls*
          rm -f code/classes/**/Test_*.cls*
          rm -f code/classes/*.xml || true

      - name: Extract static resources
        run: |
          mkdir -p code/staticresources_extracted
          for f in code/staticresources/*.resource; do
            if [ -f "$f" ]; then
              jar -xf "$f" -C "code/staticresources_extracted/$(basename "$f" .resource)" || true
            fi
          done

      - name: Run Dependency Check
        run: |
          chmod 755 ./tools/dependency-check/bin/*
          ./tools/dependency-check/bin/dependency-check.sh \
            --project "MeinServiceTL" \
            --scan "code/" \
            --exclude "**/aura/**" \
            --exclude "**/lwc/**" \
            --scan "code/staticresources/" \
            --disableOssIndex \
            --format HTML \
            --format CSV \
            --format JSON \
            --out . \
            --proxyserver=b2b-http.fpl.com \
            --proxyport=8080 \
            --nonProxyHosts=*.fpl.com \
            --cveUrlModified=https://artifactory.fpl.com/nvd/nvdcve-1.1-modified.json.gz \
            --cveUrlBase=https://artifactory.fpl.com/nvd/nvdcve-1.1-%d.json.gz

      - name: Archive Reports
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-reports
          path: |
            dependency-check-report.html
            dependency-check-report.csv
            dependency-check-report.json
